spring:
  application:
    name: slack
  datasource:
    url: jdbc:postgresql://${SLACK_DB_URL}
    username: ${SLACK_DB_USER}
    password: ${SLACK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
      use_sql_comments: true

server:
  port: 19011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

slack:
  token: ${SLACK_API_TOKEN}

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: slacks/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json